export const GET_COUNTRIES_REQUEST = "GET_COUNTRIES_REQUEST";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";
export const GET_COUNTRIES_FAIL = "GET_COUNTRIES_FAIL";

export const GET_COUNTRIES_DETAILS_REQUEST = "GET_COUNTRIES_DETAILS_REQUEST";
export const GET_COUNTRIES_DETAILS_SUCCESS = "GET_COUNTRIES_DETAILS_SUCCESS";
export const GET_COUNTRIES_DETAILS_FAIL = "GET_COUNTRIES_DETAILS_FAIL";
export const GET_COUNTRIES_DETAILS_RESET = "GET_COUNTRIES_DETAILS_RESET";
